### ISSUE TITLE
Api module breaks api

### ISSUE THREAD

**Issue by paladox** [StarCitizenTools/mediawiki-skins-Citizen#104]
Install skin and go to api.php.

There should not be an internal error but there is, debugging leads me to https://github.com/StarCitizenTools/mediawiki-skins-Citizen/blob/master/includes/api/ApiWebappManifest.php

Error states:

```
2020-05-14 20:33:53 test2 test2wiki: [29e0785fb18ded9484cde6cd] /w/api.php?action=query&format=json&origin=*&generator=search&gsrnamespace=6&iiurlheight=200&iiprop=dimensions%7Curl%7Cmediatype%7Cextmetadata%7Ctimestamp%7Cuser&prop=imageinfo&gsrsearch=test&iiurlwidth=300&gsroffset=0&gsrlimit=15   InvalidArgumentException from line 123 of /srv/mediawiki/w/includes/api/ApiModuleManager.php: $spec must define a class name
#0 /srv/mediawiki/w/includes/api/ApiModuleManager.php(79): ApiModuleManager->addModule(string, string, array)
#1 /srv/mediawiki/w/includes/api/ApiMain.php(289): ApiModuleManager->addModules(array, string)
#2 /srv/mediawiki/w/api.php(68): ApiMain->__construct(RequestContext, boolean)
#3 {main}
```

**Comment by paladox** [comment]
I think your missing getAllowedParams()

**Comment by alistair3149** [comment]
Closed after PR
