### ISSUE TITLE
Return value of Citizen\Partials\Header::getUserContributionsData() must be of the type array, null returned

### ISSUE THREAD

**Issue by ZechariahB** [StarCitizenTools/mediawiki-skins-Citizen#459]
## Describe the Bug
I cloned a recent version of mediawiki-skins-Citizen into MediaWiki's skins folder and made sure to add into LocalSettings.php
`$wgDefaultSkin = "citizen";`
`wfLoadSkin( 'Citizen' );`

Only default extensions MultimediaViewer, Renameuser, VisualEditor, are used and the error seems to not be affected by them.

~~It worked exactly as intended.~~ Its broken. Oooof.
```
MediaWiki internal error.

Original exception: [3d373126aa048fb0769f2427] /mediawiki/index.php/Special:Preferences TypeError from line 199 of /usr/share/mediawiki/skins/Citizen/includes/Partials/Header.php: Return value of Citizen\Partials\Header::getUserContributionsData() must be of the type array, null returned
Backtrace:
#0 /usr/share/mediawiki/skins/Citizen/includes/Partials/Header.php(139): Citizen\Partials\Header->getUserContributionsData()
#1 /usr/share/mediawiki/skins/Citizen/includes/Partials/Header.php(65): Citizen\Partials\Header->decoratePersonalMenu()
#2 /usr/share/mediawiki/skins/Citizen/includes/SkinCitizen.php(110): Citizen\Partials\Header->buildPersonalMenu()
#3 /usr/share/mediawiki/includes/skins/SkinMustache.php(57): SkinCitizen->getTemplateData()
#4 /usr/share/mediawiki/includes/skins/SkinTemplate.php(144): SkinMustache->generateHTML()
#5 /usr/share/mediawiki/includes/OutputPage.php(2622): SkinTemplate->outputPage()
#6 /usr/share/mediawiki/includes/MediaWiki.php(952): OutputPage->output()
#7 /usr/share/mediawiki/includes/MediaWiki.php(965): MediaWiki->{closure}()
#8 /usr/share/mediawiki/includes/MediaWiki.php(548): MediaWiki->main()
#9 /usr/share/mediawiki/index.php(53): MediaWiki->run()
#10 /usr/share/mediawiki/index.php(46): wfIndexMain()
#11 {main}

Exception caught inside exception handler: [3d373126aa048fb0769f2427] /mediawiki/index.php/Special:Preferences TypeError from line 199 of /usr/share/mediawiki/skins/Citizen/includes/Partials/Header.php: Return value of Citizen\Partials\Header::getUserContributionsData() must be of the type array, null returned
Backtrace:
#0 /usr/share/mediawiki/skins/Citizen/includes/Partials/Header.php(139): Citizen\Partials\Header->getUserContributionsData()
#1 /usr/share/mediawiki/skins/Citizen/includes/Partials/Header.php(65): Citizen\Partials\Header->decoratePersonalMenu()
#2 /usr/share/mediawiki/skins/Citizen/includes/SkinCitizen.php(110): Citizen\Partials\Header->buildPersonalMenu()
#3 /usr/share/mediawiki/includes/skins/SkinMustache.php(57): SkinCitizen->getTemplateData()
#4 /usr/share/mediawiki/includes/skins/SkinTemplate.php(144): SkinMustache->generateHTML()
#5 /usr/share/mediawiki/includes/OutputPage.php(2622): SkinTemplate->outputPage()
#6 /usr/share/mediawiki/includes/exception/MWExceptionRenderer.php(153): OutputPage->output()
#7 /usr/share/mediawiki/includes/exception/MWExceptionRenderer.php(65): MWExceptionRenderer::reportHTML()
#8 /usr/share/mediawiki/includes/exception/MWExceptionHandler.php(106): MWExceptionRenderer::output()
#9 /usr/share/mediawiki/includes/exception/MWExceptionHandler.php(185): MWExceptionHandler::report()
#10 /usr/share/mediawiki/includes/MediaWiki.php(584): MWExceptionHandler::handleException()
#11 /usr/share/mediawiki/index.php(53): MediaWiki->run()
#12 /usr/share/mediawiki/index.php(46): wfIndexMain()
#13 {main}
```

## System
 - MediaWiki version 1:1.35.4-1+deb11u2
 - Server OS: Debian 11
 - PHP version 7.4.28

**Comment by alistair3149** [comment]
Thanks for the report! Just deployed a fix and would you mind to check if it works for you?

**Comment by alistair3149** [comment]
Thanks again! It should be fixed with the latest patch. Please let me know if you run into any other issue!

**Comment by alistair3149** [comment]
Thanks again for posting the error log and bear with me!
Would you mind to check if the latest patch fix it for you?
