### ISSUE TITLE
IntlException: Constructor failed

### ISSUE THREAD

**Issue by Dianliang233** [StarCitizenTools/mediawiki-skins-Citizen#474]
## Describe the Bug
I keep getting this error after I upgraded the skin. I have tried the following troubleshooting steps:

- Revert to PHP 7
- Upgrade to PHP 8.1
- Upgrade to MW 1.38
- Revert to MW 1.37
- Checked my `date.timezone` config and made sure it's `UTC` so no invaild TZ

One thing worth noting is that an older version (1.10.0) of the skin is stilling working fine on my install. I haven't tested out which exact version introduced this but `main` branch, 1.17.5 and 1.17.4 all throws out this error.

1. Install the latest version of the skin
2. See error:

```
MediaWiki internal error.

Original exception: [19561fc8e4a5c18cc07b1e2f] /wiki/Special:%E7%89%88%E6%9C%AC IntlException: Constructor failed
Backtrace:
from /path/to/mediawiki/skins/Citizen/includes/Partials/Drawer.php(180)
#0 /path/to/mediawiki/skins/skins/Citizen/includes/Partials/Drawer.php(180): NumberFormatter->__construct()
#1 /path/to/mediawiki/skins/skins/Citizen/includes/Partials/Drawer.php(90): MediaWiki\Skins\Citizen\Partials\Drawer->getSiteStatsData()
#2 /path/to/mediawiki/skins/skins/Citizen/includes/SkinCitizen.php(124): MediaWiki\Skins\Citizen\Partials\Drawer->getDrawerTemplateData()
#3 /path/to/mediawiki/skins/includes/skins/SkinMustache.php(56): MediaWiki\Skins\Citizen\SkinCitizen->getTemplateData()
#4 /path/to/mediawiki/skins/includes/skins/SkinTemplate.php(144): SkinMustache->generateHTML()
#5 /path/to/mediawiki/skins/includes/OutputPage.php(2644): SkinTemplate->outputPage()
#6 /path/to/mediawiki/skins/includes/MediaWiki.php(944): OutputPage->output()
#7 /path/to/mediawiki/skins/includes/MediaWiki.php(957): MediaWiki::{closure}()
#8 /path/to/mediawiki/skins/includes/MediaWiki.php(564): MediaWiki->main()
#9 /path/to/mediawiki/skins/index.php(53): MediaWiki->run()
#10 /path/to/mediawiki/skins/index.php(46): wfIndexMain()
#11 {main}

Exception caught inside exception handler: [19561fc8e4a5c18cc07b1e2f] /wiki/Special:%E7%89%88%E6%9C%AC IntlException: Constructor failed
Backtrace:
from /path/to/mediawiki/skins/Citizen/includes/Partials/Drawer.php(180)
#0 /path/to/mediawiki/skins/skins/Citizen/includes/Partials/Drawer.php(180): NumberFormatter->__construct()
#1 /path/to/mediawiki/skins/skins/Citizen/includes/Partials/Drawer.php(90): MediaWiki\Skins\Citizen\Partials\Drawer->getSiteStatsData()
#2 /path/to/mediawiki/skins/skins/Citizen/includes/SkinCitizen.php(124): MediaWiki\Skins\Citizen\Partials\Drawer->getDrawerTemplateData()
#3 /path/to/mediawiki/skins/includes/skins/SkinMustache.php(56): MediaWiki\Skins\Citizen\SkinCitizen->getTemplateData()
#4 /path/to/mediawiki/skins/includes/skins/SkinTemplate.php(144): SkinMustache->generateHTML()
#5 /path/to/mediawiki/skins/includes/OutputPage.php(2644): SkinTemplate->outputPage()
#6 /path/to/mediawiki/includes/exception/MWExceptionRenderer.php(158): OutputPage->output()
#7 /path/to/mediawiki/includes/exception/MWExceptionRenderer.php(77): MWExceptionRenderer::reportHTML()
#8 /path/to/mediawiki/includes/exception/MWExceptionHandler.php(107): MWExceptionRenderer::output()
#9 /path/to/mediawiki/includes/exception/MWExceptionHandler.php(202): MWExceptionHandler::report()
#10 /path/to/mediawiki/includes/MediaWiki.php(583): MWExceptionHandler::handleException()
#11 /path/to/mediawiki/index.php(53): MediaWiki->run()
#12 /path/to/mediawiki/index.php(46): wfIndexMain()
#13 {main}
```

## System
_Please complete the following information:_
 - MediaWiki version [e.g. v1.33.1] v1.38
 - Server OS: [e.g. Debian 10] CentOS 7.9.2009
 - PHP version [e.g. v7.2.19-0ubuntu0.18.04.2] 8.0.17 (fpm-fcgi)

**Comment by alistair3149** [comment]
Have you installed php-intl and ICU? If yes, what versions are they on?

**Comment by lakejason0** [comment]
I'm also experiencing this, and it's like
<html>
<body>
<h2 style="box-sizing: border-box; font-family: sans-serif; font-weight: 500; line-height: 1.1; color: rgb(34, 34, 34); margin: 0px; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a name="module_intl" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 51, 51); text-decoration: none; border: 0px;">intl</a></h2>

Internationalization support | enabled
-- | --
ICU version | 50.2
ICU Data version | 50.2
ICU TZData version | 2018e
ICU Unicode version | 6.2


</body>
</html>

**Comment by Rushster** [comment]
Same problem here. On php 7.4.29 and php-intl and ICU is installed.

**Comment by Rushster** [comment]
Added this to LocalSettings....

$wgCitizenUseNumberFormatter = 'false';

If that's right then I am still getting the error.
