### ISSUE TITLE
Fatal error: skin.json

### ISSUE THREAD

**Issue by sibogatovr** [StarCitizenTools/mediawiki-skins-Citizen#660]
Good evening! When installing the skin, I get this error, MediaWiki version 1.39.3. Thanks.

Fatal error: Uncaught Exception: Unable to open file /var/www/u2072604/data/www/tl.rinyasuper.ru/skins/Citizen/skin.json: filemtime(): stat failed for /var/www/u2072604/data/www/tl.rinyasuper.ru/skins/Citizen/skin.json in /var/www/u2072604/data/www/tl.rinyasuper.ru/includes/registration/ExtensionRegistry.php:199 Stack trace: #0 /var/www/u2072604/data/www/tl.rinyasuper.ru/includes/GlobalFunctions.php(86): ExtensionRegistry->queue('/var/www/u20726...') #1 /var/www/u2072604/data/www/tl.rinyasuper.ru/LocalSettings.php(133): wfLoadSkin('Citizen') #2 /var/www/u2072604/data/www/tl.rinyasuper.ru/includes/Setup.php(218): require_once('/var/www/u20726...') #3 /var/www/u2072604/data/www/tl.rinyasuper.ru/includes/WebStart.php(86): require_once('/var/www/u20726...') #4 /var/www/u2072604/data/www/tl.rinyasuper.ru/index.php(44): require('/var/www/u20726...') #5 {main} thrown in /var/www/u2072604/data/www/tl.rinyasuper.ru/includes/registration/ExtensionRegistry.php on line 199

**Comment by alistair3149** [comment]
That seems like a configuration issue on your server or MW setup. I am not sure what the exact cause is though.
