### ISSUE TITLE
MediaWiki internal error.

### ISSUE THREAD

**Issue by firenotfading** [StarCitizenTools/mediawiki-skins-Citizen#710]
Please help,how do i fix this,im a noob.

MediaWiki internal error.

Original exception: [8a69ac25513e885d6b328a39] /index.php?title=%E9%A6%96%E9%A1%B5 IntlException: Constructor failed
Backtrace:
from /www/wwwroot/life.laoyiwiki.cn/skins/Citizen/includes/Partials/Drawer.php(84)
#0 /www/wwwroot/life.laoyiwiki.cn/skins/Citizen/includes/Partials/Drawer.php(84): NumberFormatter->__construct()
#1 /www/wwwroot/life.laoyiwiki.cn/skins/Citizen/includes/SkinCitizen.php(92): MediaWiki\Skins\Citizen\Partials\Drawer->getSiteStatsData()
#2 /www/wwwroot/life.laoyiwiki.cn/includes/skins/SkinMustache.php(62): MediaWiki\Skins\Citizen\SkinCitizen->getTemplateData()
#3 /www/wwwroot/life.laoyiwiki.cn/includes/skins/SkinTemplate.php(181): SkinMustache->generateHTML()
#4 /www/wwwroot/life.laoyiwiki.cn/includes/OutputPage.php(2899): SkinTemplate->outputPage()
#5 /www/wwwroot/life.laoyiwiki.cn/includes/MediaWiki.php(941): OutputPage->output()
#6 /www/wwwroot/life.laoyiwiki.cn/includes/MediaWiki.php(576): MediaWiki->main()
#7 /www/wwwroot/life.laoyiwiki.cn/index.php(50): MediaWiki->run()
#8 /www/wwwroot/life.laoyiwiki.cn/index.php(46): wfIndexMain()
#9 {main}

Exception caught inside exception handler: [8a69ac25513e885d6b328a39] /index.php?title=%E9%A6%96%E9%A1%B5 IntlException: Constructor failed
Backtrace:
from /www/wwwroot/life.laoyiwiki.cn/skins/Citizen/includes/Partials/Drawer.php(84)
#0 /www/wwwroot/life.laoyiwiki.cn/skins/Citizen/includes/Partials/Drawer.php(84): NumberFormatter->__construct()
#1 /www/wwwroot/life.laoyiwiki.cn/skins/Citizen/includes/SkinCitizen.php(92): MediaWiki\Skins\Citizen\Partials\Drawer->getSiteStatsData()
#2 /www/wwwroot/life.laoyiwiki.cn/includes/skins/SkinMustache.php(62): MediaWiki\Skins\Citizen\SkinCitizen->getTemplateData()
#3 /www/wwwroot/life.laoyiwiki.cn/includes/skins/SkinTemplate.php(181): SkinMustache->generateHTML()
#4 /www/wwwroot/life.laoyiwiki.cn/includes/OutputPage.php(2899): SkinTemplate->outputPage()
#5 /www/wwwroot/life.laoyiwiki.cn/includes/exception/MWExceptionRenderer.php(184): OutputPage->output()
#6 /www/wwwroot/life.laoyiwiki.cn/includes/exception/MWExceptionRenderer.php(103): MWExceptionRenderer::reportHTML()
#7 /www/wwwroot/life.laoyiwiki.cn/includes/exception/MWExceptionHandler.php(132): MWExceptionRenderer::output()
#8 /www/wwwroot/life.laoyiwiki.cn/includes/exception/MWExceptionHandler.php(249): MWExceptionHandler::report()
#9 /www/wwwroot/life.laoyiwiki.cn/includes/MediaWiki.php(595): MWExceptionHandler::handleException()
#10 /www/wwwroot/life.laoyiwiki.cn/index.php(50): MediaWiki->run()
#11 /www/wwwroot/life.laoyiwiki.cn/index.php(46): wfIndexMain()
#12 {main} Behavior

## System
_Please complete the following information:_
 - MediaWiki version [e.g. v1.33.1]
 - Server OS: [e.g. Debian 10]
 - Installed extensions and versions [e.g. SemanticMediaWiki 3.0, WikiSEO 2.3.1, etc.]
 - PHP version [e.g. v7.2.19-0ubuntu0.18.04.2]

**Comment by alistair3149** [comment]
Duplicate of #474. I will be adding a patch to stop it from throwing an exception, but it won't address the root cause since it is related to the PHP Intl extension itself.
